# Generated by Django 5.0 on 2023-12-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classificationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField(blank=True, null=True)),
                ('gender', models.FloatField(blank=True, null=True)),
                ('impulse', models.FloatField(blank=True, null=True)),
                ('pressurehigh', models.FloatField(blank=True, null=True)),
                ('presurelow', models.FloatField(blank=True, null=True)),
                ('glucose', models.FloatField(blank=True, null=True)),
                ('kcm', models.FloatField(blank=True, null=True)),
                ('troponin', models.FloatField(blank=True, null=True)),
                ('classification', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
