# Generated by Django 5.0 on 2023-12-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlfinalproject', '0002_rename_presurelow_classificationtable_pressurelow'),
    ]

    operations = [
        migrations.CreateModel(
            name='regressionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnitude', models.FloatField(blank=True, null=True)),
                ('cdi', models.FloatField(blank=True, null=True)),
                ('mmi', models.FloatField(blank=True, null=True)),
                ('sig', models.FloatField(blank=True, null=True)),
                ('dmin', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('Year', models.FloatField(blank=True, null=True)),
                ('Month', models.FloatField(blank=True, null=True)),
                ('tsunami', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
