# Generated by Django 5.0 on 2023-12-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlfinalproject', '0004_rename_month_regressiontable_carat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regressiontable',
            name='price',
        ),
    ]
