# Generated by Django 5.0 on 2023-12-14 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlfinalproject', '0006_regressiontable_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regressiontable',
            name='price',
        ),
    ]
